<!DOCTYPE html>
<html>
	<head>
		<link href="{{ Global.DashboardViews }}css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="{{ Global.DashboardViews }}css/main.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
	<div class="clearfix mainWrapper">
		<div class="col-lg-12 header">
			<ul>
				<!--<li>
					<span class="glyphicon glyphicon-th"></span>
				</li>
				<li>
					<span class="glyphicon glyphicon-tasks"></span>
				</li>-->
			</ul>
		</div>
		<div class="col-lg-1 sidebar">
		<ul>

			{% for item in sidebar.getAll %}
		        <li 
		        	{% if item.getCustom('sitebarAjax') != false %}
		        		sidebar-utilize-ajax="true" 
		        		sidebar-ajax="{{ item.getModule.getPackage }}/{{ item.getModule.getName }}" 
		        		sidebar-class="{{ item.getCustom('sitebarAjax').class }}" 
		        		sidebar-method="{{ item.getCustom('sitebarAjax').method }}" 
		        		sidebar-args="{{ item.getCustom('sitebarAjax').args|json_encode() }}" 
		        		sidebar-callback="{{ item.getCustom('ajaxCallback') }}"
		        	{% endif %}
		        >
		        	<div>
		        	<span class="glyphicon glyphicon-{{ item.getIcon }}"></span>
		        	{{ item.getTitle }}
		        	</div>
		        </li>
		    {% endfor %}

		</ul>

		</div>
		<div class="col-lg-11 content">
			<div class="subSide pull-left"></div>
			<div class="bar">Hej med dig kaj</div>
		</div>
	</div>

	<!--Javascript-->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
	<script src="{{ Global.DashboardViews }}js/bootstrap.min.js" type="text/javascript"></script>
	<script type="text/javascript">
		function sizeHeight() {
		$('.mainWrapper .sidebar, .mainWrapper .content, .mainWrapper .subSide')
			.height( parseInt($(window).height()) - parseInt($('.mainWrapper .header').height() ) );
		}
		$(function() {

		$('.mainWrapper .sidebar, .mainWrapper .content, .mainWrapper .subSide')
			.height( parseInt($(window).height()) - parseInt($('.mainWrapper .header').height() ) );

			$(window).resize(function() { sizeHeight(); });

			$('.sidebar li[sidebar-utilize-ajax="true"]').each(function() {
				var call 		= $(this).attr('sidebar-ajax');
				var clasS 		= $(this).attr('sidebar-class');
				var method 		= $(this).attr('sidebar-method');
				var args 		= $(this).attr('sidebar-args');
				var callback 	= $(this).attr('sidebar-callback');

				$(this).click(function() {
					$.ajax({
					    url : "/Module/"+call,
					    type: "POST",
					    data : { "class" : clasS, "method" : method, args : args},
					    success: function(data)
					    {
					    	$('.subSide').html(data);
					    	if( callback != "" ) { eval(callback+"()"); }
					    	$('.subSide').show().css('width','0%').animate({ 'width' : '20%' }, 1000,function() {
					    		
					    	});
					        
					    },
					    error: function (jqXHR)
					    {
					 
					    }
					});
				});

			});

		});
	</script>
	</body>
</html>