<!DOCTYPE html>
<html>
	<head>
		<link href="{{ Global.DashboardViews }}css/bootstrap.min.css" rel="stylesheet" type="text/css" />
		<link href="{{ Global.DashboardViews }}css/main.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
	<div class="clearfix mainWrapper">
		<div class="col-lg-12 header">
			<ul>
				<!--<li>
					<span class="glyphicon glyphicon-th"></span>
				</li>
				<li>
					<span class="glyphicon glyphicon-tasks"></span>
				</li>-->
			</ul>
		</div>
		<div class="col-lg-1 sidebar">
		<ul>

			{% for item in sidebar.getAll %}
		        <li 
		        	{% if item.getCustom('sitebarAjax') != false %}
		        		sidebar-utilize-ajax="true" 
		        		sidebar-ajax="{{ item.getModule.getPackage }}/{{ item.getModule.getName }}" 
		        		sidebar-class="{{ item.getCustom('sitebarAjax').class }}" 
		        		sidebar-method="{{ item.getCustom('sitebarAjax').method }}" 
		        		sidebar-args="{{ item.getCustom('sitebarAjax').args|json_encode() }}" 
		        		sidebar-callback="{{ item.getCustom('ajaxCallback') }}"
		        	{% endif %}
		        >
		        	<div>
		        	<span class="glyphicon glyphicon-{{ item.getIcon }}"></span>
		        	{{ item.getTitle }}
		        	</div>
		        </li>
		    {% endfor %}

		</ul>

		</div>
		<div class="col-lg-11 content">
			<div class="subSide pull-left"></div>
			<div class="innerContent pull-left minusbar">
				<div class="bar" >Hej med dig kaj</div>
			</div>
		</div>
	</div>

	<!--Javascript-->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js" type="text/javascript"></script>
	<script src="{{ Global.DashboardViews }}js/bootstrap.min.js" type="text/javascript"></script>
	<script type="text/javascript">
		function sizeHeight() {
		$('.mainWrapper .sidebar, .mainWrapper .content, .mainWrapper .subSide')
			.height( parseInt($(window).height()) - parseInt($('.mainWrapper .header').height() ) );
		}
		function initContentCalls() {
			$('[content-utilize-ajax="true"]').each(function() {
				var call 		= $(this).attr('content-ajax');
				var clasS 		= $(this).attr('content-class');
				var method 		= $(this).attr('content-method');
				var args 		= $(this).attr('content-args');
				var callback 	= $(this).attr('content-callback');
				var selector	= this;
				if( $(this).find('>a').length > 0 ) {
					selector = $(this).children('a');
				}
				$(selector).on('click',function() {
					contentLoading(true);
					$.ajax({
					    url : "/Module/"+call,
					    type: "POST",
					    data : { "class" : clasS, "method" : method, args : args},
					    success: function(data)
					    {
					    	$('.innerContent').html(data);
					    	contentLoading(false);
					    	if( callback != "" ) { eval(callback+"()"); }

					        
					    },
					    error: function (jqXHR)
					    {
					 
					    }
					});
				});

			});
		}

		function openSideBar() {
			$('.minusbar').each(function() {
				$(this).css('width','80%');
			});

			$('.subSide').show().css('width','0%').animate({ 'width' : '20%' }, 1000);
		}

		function contentLoading(show) {
			obj = $('.content .iAmLoading');
			if( obj.length > 0 && show == false) {
				obj.fadeOut('slow');
			} else {
				if( obj.length > 0 && show == true) {
					obj.fadeIn('slow');
				} else {
					var overlay = $('<div></div>').hide().css(
							{ 
								'position' : 'absolute',
								'background-color' : 'rgba(0,0,0,0.5)',
								'top' : '0px',
								'bottom' : '0px',
								'left' : '0px',
								'right' : '0px' }).addClass('iAmLoading').prependTo('.content');
					var msg = $('<div></div>').html('Vent venligst..').css(
									{ 
										'color' : '#fff',
										'position' : 'fixed',
										'top' : '50%',
										'left' : '50%',
										}).appendTo(overlay);
					msg.css({'margin-top' : '-'+(msg.height()/2),
										'margin-left' : '-'+(msg.width()/2) })
				overlay.fadeIn('slow');
				}
			}
		}
		$(function() {
			initContentCalls();

		$('.mainWrapper .sidebar, .mainWrapper .content, .mainWrapper .subSide')
			.height( parseInt($(window).height()) - parseInt($('.mainWrapper .header').height() ) );

			$(window).resize(function() { sizeHeight(); });

			$('.sidebar li[sidebar-utilize-ajax="true"]').each(function() {
				var call 		= $(this).attr('sidebar-ajax');
				var clasS 		= $(this).attr('sidebar-class');
				var method 		= $(this).attr('sidebar-method');
				var args 		= $(this).attr('sidebar-args');
				var callback 	= $(this).attr('sidebar-callback');

				$(this).click(function() {
					$.ajax({
					    url : "/Module/"+call,
					    type: "POST",
					    data : { "class" : clasS, "method" : method, args : args},
					    success: function(data)
					    {
					    	$('.subSide').html(data);
					    	if( callback != "" ) { eval(callback+"()"); }
					    	initContentCalls();
					    	
					    	openSideBar();
					        
					    },
					    error: function (jqXHR)
					    {
					 
					    }
					});
				});

			});

		});
	</script>
	</body>
</html>