<div style="margin-top:10px; font-size:14px; margin-left:5px; margin-right:5px; border-bottom:1px solid #fff; padding-bottom:5px;">
  <span class="addNewPage"><span class="glyphicon glyphicon-plus"></span> Tilføj side</span>
   
   <span class="glyphicon glyphicon-transfer" style="margin-left:20px;"></span> Eksporter
</div>
<div class="helper" style="margin-top:10px; font-size:14px; margin-left:5px; margin-right:5px; border-bottom:1px solid #fff; padding-bottom:5px; display:none;">
	<div class="form-group">
		<label>Sidenavn</label>
		<input type="text" name="pageName" class="form-controll" />
	</div>
</div>
<div class="tree">

    {{ menu|raw }}
</div>
<script type="text/javascript">
	function TreeReady() {

		$('.tree li').each(function() {
			if( $(this).children('ul').length > 0 ) {
				$(this).prepend('<span class="trigger glyphicon glyphicon-expand" style="cursor:pointer;"></span>');
			}
		});

		$('.addNewPage').click(function() {
			$('.helper').slideDown('slow');
		});

	    $('.tree li li').hide();
	    $('.tree li .trigger').on('click', function (e) {
	    	if( $(this).parent().children('ul').length > 0 ) {

	        	var children = $(this).parent().find('> ul > li');
	        	if (children.is(":visible")) {
	        		$(this).removeClass('glyphicon-collapse-down').addClass('glyphicon-expand');
	        		children.hide('fast');
	        	} else {
	        		$(this).removeClass('glyphicon-expand').addClass('glyphicon-collapse-down');
	        		children.show('fast');
	        	}
	        	e.stopPropagation();
	        }
	    });
	}
</script>