<div class="bar ali">
		  <a href="javascript:void(0);" onClick="$('#editPlaceholderForm').submit();">
		  	<span class="glyphicon glyphicon-floppy-saved"></span> Gem
		  </a>
		  <a href="#">
		  	<span class="glyphicon glyphicon-remove-circle"></span> Annuler
		  </a>
</div>

<div class="bar">
{% if hasForm == true %}
	<form action="" method="post" id="editPlaceholderForm">
{% endif %}

	{{ objectEdit|raw }}

{% if hasForm == true %}
	</form>
{% endif %}

</div>


