<div class="bar ali dark">
	<b>{{ page.title }}</b>
</div>

<div class="bar ali">
	<div style="display:inline-block;">
		<span style="color:#fff; font-size:48px;" class="glyphicon glyphicon-list-alt"></span>
	</div>
	<div style="display:inline-block;">
		<span style="color:#fff; font-size:48px;" class="glyphicon glyphicon-cog"></span>
	</div>
</div>

<div class="bar">
{% for ph in page.placeholders().get() %}
	<div class="panel panel-default">
	      <div class="panel-heading">{{ ph.title }}</div>

	      <table class="table">
	        <thead>
	          <tr>
	            <th>#</th>
	            <th>Navn</th>
	            <th>Modul</th>
	            <th>Oprettet af</th>
	          </tr>
	        </thead>
	        <tbody>
	        {% for pho in ph.objects().get() %}
	          <tr>
	            <td>{{ pho.placeholder_object_id }}</td>
	            <td>{{ pho.title }}</td>
	            <td>{{ pho.module().get().name }}</td>
	            <td>Jonas</td>
	          </tr>
	        {% endfor %}

	        </tbody>
	      </table>

	</div>
{% endfor %}

</div>

<div class="bar ali dark">
<b>Add</b>
 {% for mod in Global.Modules.allModulesSingle() %}
 	{% if mod.getConfig().frontendOptions != false %}
 		<a href="javascript:void(0);" class="option" attr-package="{{ mod.getPackage() }}" attr-module="{{ mod.getName() }}">{{ mod.getName() }}</a>
 	{% endif %}
 {% endfor %}
</div>
<div class="bar ali displayoptions">
</div>

<script type="text/javascript">
	function editPageReady() {
		$('.option').on('click',function() {
			var that = this;
			$.post('/Module/Base/Pages', 
					{ 
						'method' : 'ajaxModuleOptions',
						'args' : 
									[
										$(that).attr('attr-package'),
										$(that).attr('attr-module'),
									]
					}, function(data) { $('.displayoptions').html(data); });
		});
	}
</script>